apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: lets-encrypt
spec:
    acme:
        email: connect@sajankumarv.com # Please your company's or your email address
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: lets-encrypt-prod
        solvers:
            - http01:
                  ingress:
                      class: public
