apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: lets-encrypt-staging
spec:
    acme:
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        email: username@yourdomain.com # Please your company's or your email address
        privateKeySecretRef:
            name: lets-encrypt-staging
        solvers:
            - http01:
                  ingress:
                      class: public
